### ISSUE TITLE
Troubleshoot a record that won't update in Solr

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geomg#228]
This item (https://geo.btaa.org/catalog/9f959750-994e-0134-2096-0050569601ca-a) has the wrong language code. However, editing it in GEOMG does not result in changes in the Geoportal. This behavior is not being observed by other records so far.

to check:
- [x] does this record have weird coordinates?
~~- [ ] is there missing required metadata?~~
~~- [ ] is the IIIF link throwing errors?~~

**Comment by karenmajewicz** [comment]
I deleted the Bounding Box value for this record and it immediately updated in Solr. The value was the default of `-180,-90,180,90`. I tested other records that have this value and they also will not update. I can edit them in GEOMG, but the changes are not pushed to Solr.

These records previously were blank in the Bounding Box field. When we reindexed for the multiple geometry work, we must have added `-180,-90,180,90` as a default value.  However, Solr must not like this calculated value `POLYGON((-180 90, 180 90, 180 -90, -180 -90, -180 90))` in the new geometry field. Options:

-  batch replace `-180,-90,180,90` to something like `-179.9,-89.9,179.9,89.9`
OR
-  remove `-180,-90,180,90` altogether

I should be able to do all of this via exports & imports via GEOMG.

**Comment by ewlarson** [comment]
This Lucene issue describes why it is ultimately a bad polygon: https://github.com/apache/lucene/issues/9568

We don't see these kinds of errors in GEOMG because of how Kithe/Traject index documents into Solr via batches and with configuration settings to skip errors to continue processing large batches. More info here:
https://github.com/traject/traject/issues/221

We could take a couple directions here:

1. Write a database migration to remove these Bounding Boxes from the database
2. Update our Solr index mapping to remove these Bounding Boxes from Solr -- essentially, not send them if they're the entire world.

Thoughts?

**Comment by karenmajewicz** [comment]
Fixing these retroactively shouldn't be too hard. However, we will likely get batches of metadata in the future that contain this value. Would option 2 be a persistent fix? That would be ideal.

**Comment by karenmajewicz** [comment]
https://geomg.lib.umn.edu/documents/p16022coll230:605

**Comment by karenmajewicz** [comment]
Tested these options on IDs `p16022coll230:605` and `05d-03` and all these seem to be working;

- [ ] deleted Bounding Box and Geometry values to leave empty
- [ ] manually added`-180,-90,180,90` to BBox; -> `ENVELOPE(-180,180,90,-90)` is generated by the app
- [ ] manually added ENVELOPE(-180,180,90,-90) to Geometry, left BBox blank
- [ ] manually added POLYGON((-180 90, 180 90, 180 -90, -180 -90, -180 90)) to Geometry, received the helpful error message: 

> Locn geometry Invalid polygon: all points are coplanar input, Solr will not index

**Comment by ewlarson** [comment]
Closing via v0.15.1
