### ISSUE TITLE
Fix layout on Adv Search form

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geomg#229]
<img width="599" alt="Screen Shot 2022-09-21 at 5 05 10 PM" src="https://user-images.githubusercontent.com/2367677/191618839-60047c7b-ebe9-4fe6-b812-c1064894d536.png">

**Comment by ewlarson** [comment]
This view uses Chosen.js to present these options. If there is a JS error on the page, chosen will not run and we'll see these multi-valued selects. The fix is to fix our javascript, and afterwards the page will render correctly like this:

<img width="768" alt="Screen Shot 2022-11-14 at 4 11 40 PM" src="https://user-images.githubusercontent.com/69827/201778874-9978dcfe-7174-417e-9d71-53d85340d8e8.png">

Fix is live on https://geomgdev.lib.umn.edu/search
